name: chainercv
channels:
- !!python/unicode
  'menpo'
- !!python/unicode
  'defaults'
- !!python/unicode
  'conda-forge'
- !!python/unicode
  'anaconda'
dependencies:
  - python=3.5
  - Cython
  - opencv=3.2.0
  - pillow=4.2.1
  - chainer=2.1.0
  - matplotlib
  - numpy
  - Pillow
